/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Deepansh
 */

import javax.swing.*;
import java.awt.Image;
import java.awt.Color;
public class Currency_App extends javax.swing.JFrame {

    boolean darkMode = false;
    String [] currencyUnits = {
        "Units","US Dollar","Nigerian Naira","Brazialian Real","Canadian Dollar","Kenyan Shilling","Indonesian Rupiah","Indian Rupee","Philippine Pisco","Pakistani Rupee"
    };

    double US_Dollar = 1.36;
    double Nigerian_Naira = 2034.88;
    double Brazilian_Real = 7.26;
    double Canadian_Dollar = 1.88;
    double Kenyan_Shilling = 176.22;
    double Indonesian_Rupiah = 22536.09;
    double Indian_Rupee = 120.12;
    double Philippine_Peso = 77.79;
    double Pakistani_Rupee = 384.60;
    /**
     * Creates new form Currency_App
     */
    public Currency_App() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        secondCountry = new javax.swing.JComboBox<>();
        to = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        secondCurrencyUnit = new javax.swing.JLabel();
        firstCurrencyUnit = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        ConvertBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        darkModeBtn = new javax.swing.JButton();
        firstCountry = new javax.swing.JComboBox<>();
        leftArrow = new javax.swing.JLabel();
        rightArrow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        secondCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One....", "USA", "Nigeria", "Brazil", "Canada", "Indonesia", "India", "Philippine", "Pakistan" }));
        secondCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                secondCountryItemStateChanged(evt);
            }
        });

        to.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        to.setText("To Country");

        from.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        from.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        from.setText("From Country");

        secondCurrencyUnit.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        secondCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondCurrencyUnit.setText("Units");

        firstCurrencyUnit.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        firstCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstCurrencyUnit.setText("Units");

        exitBtn.setFont(new java.awt.Font("Sans Serif Collection", 3, 12)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        ConvertBtn.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        ConvertBtn.setText("CONVERT");
        ConvertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Currency Converter");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 3, 610, 60));

        darkModeBtn.setBackground(new java.awt.Color(60, 179, 117));
        darkModeBtn.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        darkModeBtn.setForeground(new java.awt.Color(255, 255, 255));
        darkModeBtn.setText("Dark Mode");
        darkModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(darkModeBtn, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(darkModeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 100, 30));

        firstCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One....", "USA", "Nigeria", "Brazil", "Canada", "Indonesia", "India", "Philippine", "Pakistan" }));
        firstCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                firstCountryItemStateChanged(evt);
            }
        });
        firstCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCountryActionPerformed(evt);
            }
        });

        leftArrow.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        leftArrow.setForeground(new java.awt.Color(51, 51, 51));
        leftArrow.setText("<--");

        rightArrow.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        rightArrow.setForeground(new java.awt.Color(51, 51, 51));
        rightArrow.setText("-->");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(firstCurrencyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(from, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(firstCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(rightArrow))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(leftArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(to, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(t2)
                                .addComponent(secondCurrencyUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(secondCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(ConvertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(leftArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secondCurrencyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstCurrencyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConvertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBtnActionPerformed
            if(firstCountry.getSelectedIndex() == 0 || secondCountry.getSelectedIndex() == 0 || t1.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"You Must Select Both Countries and must Input the Amount","Error Message",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            double amountToChange = Double.parseDouble(t1.getText());
            
            double amountInPounds = 0.0;
            
           switch(firstCountry.getSelectedItem().toString())
           {
                case "USA": 
                    amountInPounds = amountToChange / US_Dollar;
                    break;
                case "Nigeria": 
                    amountInPounds = amountToChange / Nigerian_Naira;
                    break;
                case "Brazil": 
                    amountInPounds = amountToChange / Brazilian_Real;
                    break;
                case "Canada": 
                    amountInPounds = amountToChange / Canadian_Dollar;
                    break;
                case "Kenyan": 
                    amountInPounds = amountToChange / Kenyan_Shilling;
                    break;
                case "Indonesia": 
                    amountInPounds = amountToChange / Indonesian_Rupiah;
                    break;
                case "India": 
                    amountInPounds = amountToChange / Indian_Rupee;
                    break;
                case "Philippine": 
                    amountInPounds = amountToChange / Philippine_Peso;
                    break;
                case "Pakistan": 
                    amountInPounds = amountToChange / Pakistani_Rupee;
                    break;
                default:
                    amountInPounds = 0.0;
            }
            
            double amountChanged = 0.0;
            
            switch(secondCountry.getSelectedItem().toString())
            {
                case "USA":
                    amountChanged = amountInPounds * US_Dollar;
                    break;
                case "Nigeria": 
                    amountChanged = amountInPounds * Nigerian_Naira;
                    break;
                case "Brazil": 
                    amountChanged = amountInPounds * Brazilian_Real;
                    break;
                case "Canada": 
                    amountChanged = amountInPounds * Canadian_Dollar;
                    break;
                case "Kenyan": 
                    amountChanged = amountInPounds * Kenyan_Shilling;
                    break;
                case "Indonesia": 
                    amountChanged = amountInPounds * Indonesian_Rupiah;
                    break;
                case "India": 
                    amountChanged = amountInPounds * Indian_Rupee;
                    break;
                case "Philippine": 
                    amountChanged = amountInPounds * Philippine_Peso;
                    break;
                case "Pakistan": 
                    amountChanged = amountInPounds * Pakistani_Rupee;
                    break;
                default:
                    amountChanged = 0.0;
            }
            
            String value = String.format("%.2f",amountChanged);
            t2.setText(value);
            
    }//GEN-LAST:event_ConvertBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void darkModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeBtnActionPerformed
        if (!darkMode) {
        // Switch to Dark Mode
        jPanel1.setBorder(new javax.swing.border.LineBorder(new Color(200, 200, 200), 5, true));
        getContentPane().setBackground(new Color(80,80,80));
        jPanel1.setBackground(new java.awt.Color(45, 45, 45)); // dark gray
        jLabel1.setForeground(new java.awt.Color(230, 230, 230)); // white text
        from.setForeground(new java.awt.Color(200, 200, 200));
        to.setForeground(new java.awt.Color(200, 200, 200));
        firstCurrencyUnit.setForeground(new java.awt.Color(200, 200, 200));
        secondCurrencyUnit.setForeground(new java.awt.Color(200, 200, 200));

        // TextFields
        t1.setBackground(new java.awt.Color(60, 63, 65));
        t1.setForeground(new java.awt.Color(230, 230, 230));
        t2.setBackground(new java.awt.Color(60, 63, 65));
        t2.setForeground(new java.awt.Color(230, 230, 230));

        // Buttons
        ConvertBtn.setBackground(new java.awt.Color(70, 130, 180)); // steel blue
        ConvertBtn.setForeground(Color.WHITE);
        resetBtn.setBackground(new java.awt.Color(128, 128, 128)); 
        resetBtn.setForeground(Color.WHITE);
        exitBtn.setBackground(new java.awt.Color(178, 34, 34)); // firebrick red
        exitBtn.setForeground(Color.WHITE);
        
        leftArrow.setForeground(new Color(0, 204, 255));
        rightArrow.setForeground(new Color(0, 204, 255));

        darkModeBtn.setBackground(new Color(100, 149, 237));
        darkModeBtn.setForeground(Color.WHITE);
        darkModeBtn.setText("Light Mode");
        darkMode = true;
    } else {
        // Switch back to Light Mode
        jPanel1.setBorder(new javax.swing.border.LineBorder(new Color(0, 0, 0), 5, true));
        getContentPane().setBackground(new Color(255,255,255));
        jPanel1.setBackground(new java.awt.Color(250, 250, 250)); 
        jLabel1.setForeground(Color.BLACK);
        from.setForeground(Color.BLACK);
        to.setForeground(Color.BLACK);
        firstCurrencyUnit.setForeground(Color.BLACK);
        secondCurrencyUnit.setForeground(Color.BLACK);

        t1.setBackground(Color.WHITE);
        t1.setForeground(Color.BLACK);
        darkModeBtn.setForeground(Color.WHITE);
        t2.setBackground(Color.WHITE);
        t2.setForeground(Color.BLACK);

        ConvertBtn.setBackground(new java.awt.Color(200, 200, 200));
        ConvertBtn.setForeground(Color.BLACK);
        resetBtn.setBackground(new java.awt.Color(220, 220, 220));
        resetBtn.setForeground(Color.BLACK);
        exitBtn.setBackground(new java.awt.Color(240, 128, 128));
        exitBtn.setForeground(Color.BLACK);
        
        leftArrow.setForeground(new Color(51, 51, 51));
        rightArrow.setForeground(new Color(51, 51, 51));

        darkModeBtn.setBackground(new Color(60, 179, 117));
        darkModeBtn.setForeground(Color.WHITE);
        darkModeBtn.setText("Dark Mode");
        darkMode = false;
    }
    }//GEN-LAST:event_darkModeBtnActionPerformed

    private void firstCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstCountryActionPerformed

    private void firstCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstCountryItemStateChanged
        int position = firstCountry.getSelectedIndex();
        firstCurrencyUnit.setText(currencyUnits[position]);
        // TODO add your handling code here:
    }//GEN-LAST:event_firstCountryItemStateChanged

    private void secondCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_secondCountryItemStateChanged
        int position = secondCountry.getSelectedIndex();
        secondCurrencyUnit.setText(currencyUnits[position]);
        // TODO add your handling code here:
    }//GEN-LAST:event_secondCountryItemStateChanged

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        firstCountry.setSelectedIndex(0);
        secondCountry.setSelectedIndex(0);
        t1.setText(null);
        t2.setText(null);
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertBtn;
    private javax.swing.JButton darkModeBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JComboBox<String> firstCountry;
    private javax.swing.JLabel firstCurrencyUnit;
    private javax.swing.JLabel from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leftArrow;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel rightArrow;
    private javax.swing.JComboBox<String> secondCountry;
    private javax.swing.JLabel secondCurrencyUnit;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JLabel to;
    // End of variables declaration//GEN-END:variables
}
