



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Deepansh
 */
public class My_Calc_App extends javax.swing.JFrame {

    boolean darkmode = true;
    double num1 = 0;
    double num2 = 0;
    String operator = null;
    /**
     * Creates new form My_Calc_App
     */
    public My_Calc_App() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(35, 35, 35));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T1 = new javax.swing.JTextField();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        bequal = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        bback = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        darkbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        T1.setEditable(false);
        T1.setBackground(new java.awt.Color(51, 51, 51));
        T1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        T1.setForeground(new java.awt.Color(51, 255, 0));
        T1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        T1.setText("Enter Your Query");
        T1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 0)));
        T1.setOpaque(true);
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(102, 255, 0));
        b8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b8.setForeground(new java.awt.Color(51, 51, 51));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(102, 255, 0));
        b7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b7.setForeground(new java.awt.Color(51, 51, 51));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        bdiv.setBackground(new java.awt.Color(102, 255, 0));
        bdiv.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bdiv.setForeground(new java.awt.Color(51, 51, 51));
        bdiv.setText("/");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(102, 255, 0));
        b9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b9.setForeground(new java.awt.Color(51, 51, 51));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(102, 255, 0));
        b5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b5.setForeground(new java.awt.Color(51, 51, 51));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(102, 255, 0));
        b4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b4.setForeground(new java.awt.Color(51, 51, 51));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        bmul.setBackground(new java.awt.Color(102, 255, 0));
        bmul.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bmul.setForeground(new java.awt.Color(51, 51, 51));
        bmul.setText("*");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(102, 255, 0));
        b6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b6.setForeground(new java.awt.Color(51, 51, 51));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(102, 255, 0));
        b2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 51, 51));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(102, 255, 0));
        b1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 51, 51));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        bsub.setBackground(new java.awt.Color(102, 255, 0));
        bsub.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bsub.setForeground(new java.awt.Color(51, 51, 51));
        bsub.setText("-");
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(102, 255, 0));
        b3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(51, 51, 51));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        badd.setBackground(new java.awt.Color(102, 255, 0));
        badd.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        badd.setForeground(new java.awt.Color(51, 51, 51));
        badd.setText("+");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bequal.setBackground(new java.awt.Color(102, 255, 0));
        bequal.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bequal.setForeground(new java.awt.Color(51, 51, 51));
        bequal.setText("=");
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });

        bclear.setBackground(new java.awt.Color(102, 255, 0));
        bclear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bclear.setForeground(new java.awt.Color(51, 51, 51));
        bclear.setText("CLEAR");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        bback.setBackground(new java.awt.Color(102, 255, 0));
        bback.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bback.setForeground(new java.awt.Color(51, 51, 51));
        bback.setText("BACK");
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(102, 255, 0));
        b0.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        b0.setForeground(new java.awt.Color(51, 51, 51));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bdot.setBackground(new java.awt.Color(102, 255, 0));
        bdot.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bdot.setForeground(new java.awt.Color(51, 51, 51));
        bdot.setText(".");
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Calculator");
        jLabel1.setOpaque(true);
        jLayeredPane1.setLayer(jLabel1, 1);
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 67));

        darkbtn.setBackground(new java.awt.Color(51, 255, 0));
        darkbtn.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        darkbtn.setForeground(new java.awt.Color(51, 51, 51));
        darkbtn.setText("Dark Mode");
        darkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkbtnActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(darkbtn, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(darkbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 15, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bdot, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bback, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }
        T1.setText(T1.getText() + "9");           // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "6");           // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "3");           // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("Write Your Query First");
        }
        else
        {
            num2 = Double.parseDouble(T1.getText());
            double answer = 0;        
            if(operator.equals("/"))
            {
                answer = num1 / num2;
            }
            if(operator.equals("*"))
            {
                answer = num1 * num2;
            }
            if(operator.equals("-"))
            {
                answer = num1 - num2;
            }
            if(operator.equals("+"))
            {
                answer = num1 + num2;
            }
            T1.setText("" + answer);
            operator = null;
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bequalActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "7");        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "8");           // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "4");           // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "5");           // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "1");           // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "2");           // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        T1.setText(T1.getText() + "0");           // TODO add your handling code here:
    }//GEN-LAST:event_b0ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }
        T1.setText(T1.getText() + ".");           // TODO add your handling code here:
    }//GEN-LAST:event_bdotActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        num1 = Double.parseDouble(T1.getText());
        operator = "+";
        T1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_baddActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        num1 = Double.parseDouble(T1.getText());
        operator = "-";
        T1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_bsubActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

        num1 = Double.parseDouble(T1.getText());
        operator = "*";
        T1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_bmulActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }

//        T1.setText(T1.getText() + "/");
        num1 = Double.parseDouble(T1.getText());
        operator = "/";
        T1.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_bdivActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("");
        }
        T1.setText("Enter Your Query");           // TODO add your handling code here:
    }//GEN-LAST:event_bclearActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        String text = T1.getText();
        if(text.equals("Enter Your Query") || text.equals("Write Your Query First"))
        {
            T1.setText("Write Your Query First");
        }
        else
        {
            String str = T1.getText();
            T1.setText(str.substring(0, str.length() - 1));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bbackActionPerformed

    private void darkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkbtnActionPerformed
        if(!darkmode)
        {
            getContentPane().setBackground(new java.awt.Color(0, 0, 0));
            T1.setBackground(new java.awt.Color(30, 30, 30));
            T1.setForeground(new java.awt.Color(0, 255, 0));
            jLabel1.setBackground(new java.awt.Color(30, 30, 30));
            jLabel1.setForeground(new java.awt.Color(0, 255, 0));
            darkbtn.setBackground(new java.awt.Color(51, 255, 0));
            darkbtn.setForeground(new java.awt.Color(51, 51, 51));
        
        // Update buttons
            for (java.awt.Component comp : getContentPane().getComponents())
            {
                if (comp instanceof javax.swing.JButton)
                {
                    comp.setBackground(new java.awt.Color(51, 255, 0));
                    comp.setForeground(new java.awt.Color(51, 51, 51));
//                    comp.setBackground(new java.awt.Color(60, 60, 60));
//                    comp.setForeground(new java.awt.Color(0, 255, 0));
                }
            }
            darkbtn.setText("Light Mode"); // Change button text
            darkmode = true;
        } 
        else 
        {    
        // Light Mode ON
            getContentPane().setBackground(new java.awt.Color(240, 240, 240));
            T1.setBackground(new java.awt.Color(255, 255, 255));
            T1.setForeground(new java.awt.Color(0, 0, 0));
            jLabel1.setBackground(new java.awt.Color(255, 255, 255));
            jLabel1.setForeground(new java.awt.Color(0, 0, 0));
            darkbtn.setBackground(new java.awt.Color(200, 200, 200));
            darkbtn.setForeground(new java.awt.Color(0, 0, 0));
        
            for (java.awt.Component comp : getContentPane().getComponents())
            {
                if (comp instanceof javax.swing.JButton)
                {
                    comp.setBackground(new java.awt.Color(200, 200, 200));
                    comp.setForeground(new java.awt.Color(0, 0, 0));
                }
            }
            darkbtn.setText("Dark Mode");
            darkmode = false;
        }
    }//GEN-LAST:event_darkbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set th e Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(My_Calc_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(My_Calc_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(My_Calc_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(My_Calc_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new My_Calc_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bback;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bsub;
    private javax.swing.JButton darkbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
