import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.SwingUtilities;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Deepansh
 */
public class Client_Side_Chat_App extends javax.swing.JFrame {

    boolean darkMode = false;
//    static ServerSocket ss;
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dout;
    /**
     * Creates new form Client_Side_Chat_App
     */
    public Client_Side_Chat_App() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        // Get frame dimensions
        int frameWidth = getWidth();
        int frameHeight = getHeight();

        // Calculate position
        int x = screenWidth - frameWidth;
        int y = (screenHeight - frameHeight) / 2;

        setLocation(x, y);
//        startReadingThread();
    }
    
    private void startReadingThread(){
        Thread readThread = new Thread(() -> {
            try {
                String msgin = "";
                while ((msgin = dis.readUTF())!= null) {
//                    msgin = dis.readUTF();
                    String finalMsgin = msgin;
                    SwingUtilities.invokeLater(() -> msg_area.append("\n @Server: " + finalMsgin));
                }
            } catch (IOException e) {
                SwingUtilities.invokeLater(() -> msg_area.append("\n Connection closed."));
            }
        });
        readThread.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chat_server = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        darkModeBtn = new javax.swing.JButton();
        msg_send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chat_server.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        chat_server.setText("Client-Side");

        msg_area.setColumns(20);
        msg_area.setRows(5);
        msg_area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jScrollPane1.setViewportView(msg_area);

        msg_text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        darkModeBtn.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        darkModeBtn.setText("Dark Mode");
        darkModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeBtnActionPerformed(evt);
            }
        });

        msg_send.setText("SEND");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(msg_text, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chat_server, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(darkModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chat_server, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darkModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(msg_text)
                    .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
//        try{
//            String msg = "";
//            msg = msg_text.getText();
//            dout.writeUTF(msg);
//            msg_text.setText("");
//        }catch(Exception e){
//            
//        }
        try {
        if (dout != null && !msg_text.getText().trim().isEmpty()) {
            String msg = msg_text.getText().trim();
            dout.writeUTF(msg);
            msg_area.append("\n @Me: " + msg);
            msg_text.setText("");
        } else {
            msg_area.append("\n [System] Cannot send message. Not connected!");
        }
    } catch (Exception e) {
        msg_area.append("\n [System] Error sending message: " + e.getMessage());
    }
    }//GEN-LAST:event_msg_sendActionPerformed

    private void darkModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeBtnActionPerformed
        if (!darkMode) {
        // Switch to Dark Mode
        getContentPane().setBackground(new java.awt.Color(45, 45, 45));

        chat_server.setForeground(new java.awt.Color(220, 220, 220));

        msg_area.setBackground(new java.awt.Color(30, 30, 30));
        msg_area.setForeground(new java.awt.Color(230, 230, 230));
//        msg_area.setCaretColor(new java.awt.Color(255, 255, 255));
        msg_area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        msg_text.setBackground(new java.awt.Color(40, 40, 40));
        msg_text.setForeground(new java.awt.Color(230, 230, 230));
//        msg_text.setCaretColor(new java.awt.Color(255, 255, 255));
        msg_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        msg_send.setBackground(new java.awt.Color(70, 130, 180));
        msg_send.setForeground(new java.awt.Color(255, 255, 255));

        darkModeBtn.setBackground(new java.awt.Color(80, 80, 80));
        darkModeBtn.setForeground(new java.awt.Color(220, 220, 220));

        darkModeBtn.setText("Light Mode");  // Toggle button text
        darkMode = true;
    } else {
        // Switch to Light Mode
        getContentPane().setBackground(new java.awt.Color(245, 245, 245));

        chat_server.setForeground(new java.awt.Color(20, 20, 20));

        msg_area.setBackground(new java.awt.Color(255, 255, 255));
        msg_area.setForeground(new java.awt.Color(20, 20, 20));
//        msg_area.setCaretColor(new java.awt.Color(0, 0, 0));
        msg_area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 3));

        msg_text.setBackground(new java.awt.Color(255, 255, 255));
        msg_text.setForeground(new java.awt.Color(20, 20, 20));
//        msg_text.setCaretColor(new java.awt.Color(0, 0, 0));
        msg_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 2));

        msg_send.setBackground(new java.awt.Color(30, 144, 255));
        msg_send.setForeground(new java.awt.Color(255, 255, 255));
//        msg_send.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 149, 237), 2));
//
        darkModeBtn.setBackground(new java.awt.Color(240, 240, 240));
        darkModeBtn.setForeground(new java.awt.Color(20, 20, 20));
//        darkModeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2));

        darkModeBtn.setText("Dark Mode");  // Toggle button text
        darkMode = false;
    }        // TODO add your handling code here:
    }//GEN-LAST:event_darkModeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Client_Side_Chat_App clientFrame = new Client_Side_Chat_App();
        clientFrame.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_Side_Chat_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_Side_Chat_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_Side_Chat_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_Side_Chat_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Client_Side_Chat_App().setVisible(true);
//            }
//        });
        
//        try{
//            String msgin = "";
//            s = new Socket("127.0.0.1",1201);          
//            dis = new DataInputStream(s.getInputStream());
//            dout = new DataOutputStream(s.getOutputStream());
//            
//            while(!msgin.equals("exit")){
//                msgin = dis.readUTF();
//                msg_area.setText(msg_area.getText() + "\n @Client : " + msgin);
//                
//            }
//            
//        }catch(Exception e){
//            
//        }
        
        try {
            s = new Socket("127.0.0.1", 1201);
            dis = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());
            
//            new Client_Side_Chat_App().startReadingThread();
            clientFrame.startReadingThread();
        } catch (IOException e) {
//            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chat_server;
    private javax.swing.JButton darkModeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    private javax.swing.JTextField msg_text;
    // End of variables declaration//GEN-END:variables
}
